server:
  port: ${PORT:8191}
spring:
  application:
    name: account-service

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
ribbon:
  eureka:
    enabled: true